### ISSUE TITLE
Broken with version 3.1.0.32

### ISSUE THREAD

**Issue by pR0Ps** [pR0Ps/Entrust-IdentityGuard-Unblocker#1]
Opens fine but will show an error message when trying to view tokens:
"The identity named XXXX has been disabled because it cannot be used on an unsecured device."

When tapping on it again:
"This identity cannot be used on an unsecured device."

**Comment by noid23** [comment]
This issue seems to have returned in version 3.5.5.72. The device in question, my phone, is not rooted or otherwise unsecured. Other applications, such as Google Wallet, that balk at rooted or unsecured devices are running just fine. If I can assist with more information, let me know what I can provide.
